Controllers/DreamCentreController.cs
using Microsoft.AspNetCore.Mvc;

namespace LoveNottiesV2.Controllers
{
    public class DreamCentreController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/FeedingEDCController.cs
using Microsoft.AspNetCore.Mvc;

namespace LoveNottiesV2.Controllers
{
    public class FeedingEDCController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using LoveNottiesV2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LoveNottiesV2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RecyclingController.cs
using Microsoft.AspNetCore.Mvc;

namespace LoveNottiesV2.Controllers
{
    public class RecyclingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<style>
    .parallax1 {
        /* The image used */
        background-image: url("https://lovenottiesstoragetest.blob.core.windows.net/backgroundimages/BgBlog");
        /* Set a specific height */
        min-height: 300px;
        /* Create the parallax scrolling effect */
        background-attachment: fixed;
        background-position: center;
        background-repeat: no-repeat;
        object-fit:scale-down;
    }

    .parallax2 {
        /* The image used */
        background-image: url("https://lovenottiesstoragetest.blob.core.windows.net/backgroundimages/ImgFeed.png");
        /* Set a specific height */
        min-height: 300px;
        /* Create the parallax scrolling effect */
        background-attachment: fixed;
        background-position: center;
        background-repeat: no-repeat;
        object-fit:scale-down;
    }

    .parallax3 {
        /* The image used */
        background-image: url("https://lovenottiesstoragetest.blob.core.windows.net/backgroundimages/BgSS");
        /* Set a specific height */
        min-height: 300px;
        /* Create the parallax scrolling effect */
        background-attachment: fixed;
        background-position: center;
        background-repeat: no-repeat;
        /*background-size: cover;*/
        object-fit: scale-down;
    }
</style>


<div class="text-center">
    <h1 class="display-4" style="padding:50px;">Welcome to Love Notties</h1>


     <div class="box">
        <div class="card bg-primary text-center" style="max-width: 20rem;">
            <div class="card-body parallax1">
                <div style="padding:75px;">
                <h4 class="card-title text-white">Dream Centre</h4>
                <a class="btn btn-info" asp-controller="DreamCentre" asp-action="Index">Goto</a>
                </div>
            </div>
        </div>
        <div class="card bg-warning text-center" style="max-width: 20rem;">
            <div class="card-body parallax2">
                <div style="padding:75px;">
                <h4 class="card-title text-white">Feeding ECD</h4>
                <a class="btn btn-info" asp-controller="FeedingEDC" asp-action="Index">Goto</a>
                </div>
            </div>
        </div>
        <div class="card bg-primary text-center col-md-5" style="max-width: 20rem;">
            <div class="card-body  parallax3">
                <div style="padding:75px;">
                <h4 class="card-title text-white">Recycling Centre</h4>
                <a class="btn btn-info" asp-controller="Recycling" asp-action="Index">Goto</a>
                </div>
            </div>
        </div>
    </div>
</div>