Models/OurPeople.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LoveNottiesV2.Models
{
    public class OurPeople
    {
        [Key]
        [DataType(DataType.Text)]
        public string OurPersonID { get; set; }

        [DataType(DataType.Text)]
        public string OurPersonFirstName { get; set; }

        [DataType(DataType.Text)]
        public string  OurPersonLastName { get; set; }

        [DataType(DataType.Text)]
        public string OurPersonTitle { get; set; }

        [DataType(DataType.Text)]
        public string OurPersonImageID { get; set; }

        [DataType(DataType.Text)]
        public string OurPersonDescription { get; set; }

        [NotMapped]
        [DisplayName("Upload File")]
        public IFormFile OurPersonImageFile { get; set; }

        [NotMapped]
        public byte[] OurPersonImageBytes { get; set; }
    }
}

Controllers/OurPeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LoveNottiesV2.Data;
using LoveNottiesV2.Models;
using LoveNottiesV2.Models.Repositories.Abstract;
using Azure.Storage.Blobs.Models;
using System.IO;

namespace LoveNottiesV2.Controllers
{
    public class OurPeopleController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IBlobService _IBlobService;
        private readonly IOurPeopleRepository _IOurPeopleRepository;

        public OurPeopleController(ApplicationDbContext context, IBlobService IBlobService, IOurPeopleRepository IOurPeopleRepository)
        {
            _context = context;
            _IBlobService = IBlobService;
            _IOurPeopleRepository = IOurPeopleRepository;
        }

        // GET: OurPeople
        public async Task<IActionResult> Index()
        {
            return View(_IOurPeopleRepository.GetAllOurPeople());
        }

        // GET: OurPeople/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ourPeople = await _context.OurPeoples
                .FirstOrDefaultAsync(m => m.OurPersonID == id);
            if (ourPeople == null)
            {
                return NotFound();
            }

            return View(ourPeople);
        }

        // GET: OurPeople/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: OurPeople/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OurPersonID,OurPersonFirstName,OurPersonLastName,OurPersonTitle,OurPersonImageID,OurPersonDescription," +
            "OurPersonImageFile")] OurPeople ourPeople)
        {
            if (ModelState.IsValid)
            {
                //Get the most recent OurPerson ID, and add 1
                var ourPeopleList = await _context.OurPeoples.ToListAsync();
                var lastPerson = ourPeopleList.LastOrDefault();
                if (lastPerson != null)
                {
                    ourPeople.OurPersonID = (Convert.ToInt32(lastPerson.OurPersonID) + 1).ToString();
                    ourPeople.OurPersonImageID = (Convert.ToInt32(lastPerson.OurPersonID) + 1).ToString();
                }
                else
                {
                    ourPeople.OurPersonID = "1";
                    ourPeople.OurPersonImageID = "1";
                }

                byte[] fileByteArray;    //1st change here
                if (ourPeople.OurPersonImageFile != null)
                {
                    using (var item = new MemoryStream())
                    {
                        ourPeople.OurPersonImageFile.CopyTo(item);
                        fileByteArray = item.ToArray(); //2nd change here

                        if (_IBlobService.DoesBlobExists(ourPeople.OurPersonImageID, BlobContainer.ourpeopleimages).Result == false)
                        {
                            await _IBlobService.UploadFileBlobAsync(fileByteArray, ourPeople.OurPersonImageID, BlobContainer.ourpeopleimages);
                        }
                    }
                }
                _context.Add(ourPeople);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ourPeople);
        }

        // GET: OurPeople/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ourPeople = await _context.OurPeoples.FindAsync(id);
            if (ourPeople == null)
            {
                return NotFound();
            }
            return View(ourPeople);
        }

        // POST: OurPeople/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("OurPersonID,OurPersonFirstName,OurPersonLastName,OurPersonTitle,OurPersonImage,OurPersonDescription")] OurPeople ourPeople)
        {
            if (id != ourPeople.OurPersonID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ourPeople);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OurPeopleExists(ourPeople.OurPersonID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ourPeople);
        }

        // GET: OurPeople/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ourPeople = await _context.OurPeoples
                .FirstOrDefaultAsync(m => m.OurPersonID == id);
            if (ourPeople == null)
            {
                return NotFound();
            }

            return View(ourPeople);
        }

        // POST: OurPeople/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var ourPeople = await _context.OurPeoples.FindAsync(id);

            //find and delete the blog image
            if (_IBlobService.DoesBlobExists(ourPeople.OurPersonImageID, BlobContainer.blogimages).Result == true)
            {
                await _IBlobService.DeleteFromBlob(ourPeople.OurPersonImageID, BlobContainer.blogimages);
            }

            _context.OurPeoples.Remove(ourPeople);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OurPeopleExists(string id)
        {
            return _context.OurPeoples.Any(e => e.OurPersonID == id);
        }
    }
}

Views/OurPeople/Create.cshtml
@model LoveNottiesV2.Models.OurPeople
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Our Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OurPersonFirstName" class="control-label">First Name</label>
                <input asp-for="OurPersonFirstName" class="form-control" />
                <span asp-validation-for="OurPersonFirstName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="OurPersonLastName" class="control-label">Last Name</label>
                <input asp-for="OurPersonLastName" class="form-control" />
                <span asp-validation-for="OurPersonLastName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="OurPersonTitle" class="control-label">Title</label>
                <input asp-for="OurPersonTitle" class="form-control" />
                <span asp-validation-for="OurPersonTitle" class="text-danger"></span>
            </div>

            <div class="form-group" style="margin-top:10px">
                <label asp-for="OurPersonImageFile" class="control-label">Upload Image</label>
                <input type="file" asp-for="OurPersonImageFile" accept="image/*" class="form-control" />
                <span asp-validation-for="OurPersonImageFile" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="OurPersonDescription" class="control-label">Description</label>
                <input asp-for="OurPersonDescription" class="form-control" />
                <span asp-validation-for="OurPersonDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Views/OurPeople/Delete.cshtml
@model LoveNottiesV2.Models.OurPeople

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OurPeople</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OurPersonFirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OurPersonFirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OurPersonLastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OurPersonLastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OurPersonTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OurPersonTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OurPersonImageID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OurPersonImageID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OurPersonDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OurPersonDescription)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OurPersonID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/OurPeople/Details.cshtml
@model LoveNottiesV2.Models.OurPeople

@{
    string fullName = Model.OurPersonFirstName + " " + Model.OurPersonLastName;
    ViewData["Title"] = fullName;
}
<body>
    <div class="m-5">
        <div class="card">
            <div class="card-header">
                <h1>@Html.DisplayFor(model => model.OurPersonFirstName) @Html.Raw(" ") @Html.DisplayFor(model => model.OurPersonLastName)</h1>
                <h6 class="card-subtitle text-muted">@Html.DisplayFor(model => model.OurPersonTitle)</h6>
            </div>

            <div class="card-body">
                <div class="box">
                    <div class="justify-content-center">
                        <image src="https://lovenottiesstoragetest.blob.core.windows.net/ourpeopleimages/@(Model.OurPersonID)" class="d-block user-select-none coverImageDetails ImageRoundBorders" height="650px" focusable="false" role="img" />
                    </div>

                    <div>
                        <dl>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.OurPersonDescription)
                            </dd>
                        </dl>
                        <div>
                            <a asp-action="Index">Back to List</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

Views/OurPeople/Edit.cshtml
@model LoveNottiesV2.Models.OurPeople

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>OurPeople</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OurPersonID" />
            <div class="form-group">
                <label asp-for="OurPersonFirstName" class="control-label"></label>
                <input asp-for="OurPersonFirstName" class="form-control" />
                <span asp-validation-for="OurPersonFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OurPersonLastName" class="control-label"></label>
                <input asp-for="OurPersonLastName" class="form-control" />
                <span asp-validation-for="OurPersonLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OurPersonTitle" class="control-label"></label>
                <input asp-for="OurPersonTitle" class="form-control" />
                <span asp-validation-for="OurPersonTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OurPersonImageID" class="control-label"></label>
                <input asp-for="OurPersonImageID" class="form-control" />
                <span asp-validation-for="OurPersonImageID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OurPersonDescription" class="control-label"></label>
                <input asp-for="OurPersonDescription" class="form-control" />
                <span asp-validation-for="OurPersonDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/OurPeople/Index.cshtml
@model IEnumerable<LoveNottiesV2.Models.OurPeople>
@using LoveNottiesV2.Models.Repositories.Abstract;
@using LoveNottiesV2.Models.Repositories.Implemented;
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@inject IBlobService _IblobService

@{
    ViewData["Title"] = "Index";
}

<style>
    .parallax {
        /* The image used */
        background-image: url("https://lovenottiesstoragetest.blob.core.windows.net/backgroundimages/BgOP");
        /* Set a specific height */
        min-height: 500px;
        /* Create the parallax scrolling effect */
        background-attachment: fixed;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>


<h1 class="justify-content-center">Our People</h1>
@if (SignInManager.IsSignedIn(User) & User.IsInRole("Manager"))
{
    <p>
        <a class="btn btn-primary" asp-action="Create">Create New</a>
    </p>
}
<body>
    <div class="parallax">
    <div class="box">
        @foreach (var item in Model)
        {
            <div class="card text-white bg-primary mb-10" style="max-width: 20rem;">
                <div class="card-header">
                    @Html.DisplayFor(modelItem => item.OurPersonFirstName)
                    @Html.Raw(" ")
                    @Html.DisplayFor(modelItem => item.OurPersonLastName)
                    @Html.Raw(" - ")
                    @Html.DisplayFor(modelItem => item.OurPersonTitle)
                </div>
                <div class="justify-content-center">
                    <image src="https://lovenottiesstoragetest.blob.core.windows.net/ourpeopleimages/@(item.OurPersonID)" class="d-block user-select-none coverImage" width="10px" height="10px" focusable="false" role="img" preserveAspectRatio="xMidYMid slice" viewBox="0 0 318 180" style="font-size:1.125rem;text-anchor:middle" />
                </div>
                <div class="card-body">
                    <h6 class="card-body ">

                        @if (item.OurPersonDescription.Length >= 75)
                        {

                            @(item.OurPersonDescription.Substring(0, 75)) <a asp-controller="OurPeople" asp-action="Details" asp-route-id="@(item.OurPersonID)">...Read More</a>
                        }
                        else
                        {
                            @(item.OurPersonDescription) <a asp-controller="OurPeople" asp-action="Details" asp-route-id="@(item.OurPersonID)">...Read More</a>
                        }
                     </h6>
                      @if (SignInManager.IsSignedIn(User) & User.IsInRole("Manager"))
                        {
                    <div>
                       
                            <a class="btn btn-outline-warning" asp-controller="OurPeople" asp-action="Edit" asp-route-id="@(item.OurPersonID)">Edit</a>
                            <a class="btn btn-outline-danger" asp-controller="OurPeople" asp-action="Delete" asp-route-id="@(item.OurPersonID)">Delete</a>
                    </div>
                        }
                </div>
            </div>
        }
    </div>
    </div>
</body>