Models/SuccessStory.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LoveNottiesV2.Models
{
    public class SuccessStory
    {
        [Key]
        [DataType(DataType.Text)]
        public string SuccessStoryID { get; set; }

        [DataType(DataType.Text)]
        public string SuccessStoryTitle { get; set; }

        [DataType(DataType.Text)]
        public string SuccessStoryImageID { get; set; }

        [DataType(DataType.Text)]
        public string SuccessStoryDescription { get; set; }

        [NotMapped]
        [DisplayName("Upload File")]
        public IFormFile SuccessStoryImageFile { get; set; }

        [NotMapped]
        public byte[] SuccessStoryImageBytes { get; set; }
    }
}

Controllers/SuccessStoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LoveNottiesV2.Data;
using LoveNottiesV2.Models;
using LoveNottiesV2.Models.Repositories.Abstract;
using Azure.Storage.Blobs.Models;
using System.IO;

namespace LoveNottiesV2.Controllers
{
    public class SuccessStoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IBlobService _IBlobService;
        private readonly ISuccessStoryRepository _ISuccessStoryRepository;

        public SuccessStoryController(ApplicationDbContext context, IBlobService IBlobService, ISuccessStoryRepository iSuccessStoryRepository)
        {
            _context = context;
            _IBlobService = IBlobService;
            _ISuccessStoryRepository = iSuccessStoryRepository;
        }

        // GET: SuccessStory
        public async Task<IActionResult> Index()
        {
            return View(_ISuccessStoryRepository.GetAllSuccessStories());
        }

        // GET: SuccessStory/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var successStory = await _context.successStories
                .FirstOrDefaultAsync(m => m.SuccessStoryID == id);
            if (successStory == null)
            {
                return NotFound();
            }

            return View(successStory);
        }

        // GET: SuccessStory/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SuccessStory/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SuccessStoryID,SuccessStoryTitle,SuccessStoryImageID,SuccessStoryDescription," +
            "SuccessStoryImageFile")] SuccessStory successStory)
        {
            if (ModelState.IsValid)
            {
                //Get the most recent blog's ID, and add 1
                var successStoryList = await _context.successStories.ToListAsync();
                var lastStory = successStoryList.LastOrDefault();
                if (lastStory != null)
                {
                    successStory.SuccessStoryID = (Convert.ToInt32(lastStory.SuccessStoryID) + 1).ToString();
                    successStory.SuccessStoryImageID = (Convert.ToInt32(lastStory.SuccessStoryID) + 1).ToString();
                }
                else
                {
                    successStory.SuccessStoryID = "1";
                    successStory.SuccessStoryImageID = "1";
                }

                byte[] fileByteArray;    //1st change here
                if (successStory.SuccessStoryImageFile != null)
                {
                    using (var item = new MemoryStream())
                    {
                        successStory.SuccessStoryImageFile.CopyTo(item);
                        fileByteArray = item.ToArray(); //2nd change here

                        if (_IBlobService.DoesBlobExists(successStory.SuccessStoryImageID, BlobContainer.successimages).Result == false)
                        {
                            await _IBlobService.UploadFileBlobAsync(fileByteArray, successStory.SuccessStoryImageID, BlobContainer.successimages);
                        }
                    }
                }
                _context.Add(successStory);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(successStory);
        }

        // GET: SuccessStory/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var successStory = await _context.successStories.FindAsync(id);
            if (successStory == null)
            {
                return NotFound();
            }
            return View(successStory);
        }

        // POST: SuccessStory/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("SuccessStoryID,SuccessStoryTitle,SuccessStoryImage,SuccessStoryDescription")] SuccessStory successStory)
        {
            if (id != successStory.SuccessStoryID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(successStory);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SuccessStoryExists(successStory.SuccessStoryID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(successStory);
        }

        // GET: SuccessStory/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var successStory = await _context.successStories
                .FirstOrDefaultAsync(m => m.SuccessStoryID == id);
            if (successStory == null)
            {
                return NotFound();
            }

            return View(successStory);
        }

        // POST: SuccessStory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var successStory = await _context.successStories.FindAsync(id);

            //find and delete the blog image
            if (_IBlobService.DoesBlobExists(successStory.SuccessStoryImageID, BlobContainer.blogimages).Result == true)
            {
                await _IBlobService.DeleteFromBlob(successStory.SuccessStoryImageID, BlobContainer.blogimages);
            }

            _context.successStories.Remove(successStory);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SuccessStoryExists(string id)
        {
            return _context.successStories.Any(e => e.SuccessStoryID == id);
        }
    }
}

Views/SuccessStory/Create.cshtml
@model LoveNottiesV2.Models.SuccessStory
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Our Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SuccessStoryTitle" class="control-label">Title</label>
                <input asp-for="SuccessStoryTitle" class="form-control" />
                <span asp-validation-for="SuccessStoryTitle" class="text-danger"></span>
            </div>

            <div class="form-group" style="margin-top:10px">
                <label asp-for="SuccessStoryImageFile" class="control-label">Upload Image</label>
                <input type="file" asp-for="SuccessStoryImageFile" accept="image/*" class="form-control" />
                <span asp-validation-for="SuccessStoryImageFile" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="SuccessStoryDescription" class="control-label">Description</label>
                <input asp-for="SuccessStoryDescription" class="form-control" />
                <span asp-validation-for="SuccessStoryDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Views/SuccessStory/Delete.cshtml
@model LoveNottiesV2.Models.SuccessStory

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SuccessStory</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SuccessStoryTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SuccessStoryTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SuccessStoryImageID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SuccessStoryImageID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SuccessStoryDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SuccessStoryDescription)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SuccessStoryID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/SuccessStory/Details.cshtml
@model LoveNottiesV2.Models.SuccessStory

@{
    ViewData["Title"] = @Html.DisplayFor(model => Model.SuccessStoryTitle);
}
<body>
    <div class="m-5">
        <div class="card">
            <div class="card-header">
                <h1>@Html.DisplayFor(model => model.SuccessStoryTitle)</h1>
            </div>

            <div class="card-body">
                <div class="box">
                    <div class="justify-content-center">
                        <image src="https://lovenottiesstoragetest.blob.core.windows.net/successimages/@(Model.SuccessStoryID)" class="d-block user-select-none coverImageDetails ImageRoundBorders" height="650px" focusable="false" role="img" />
                    </div>

                    <div>
                        <dl>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.SuccessStoryDescription)
                            </dd>
                        </dl>
                        <div>
                            <a asp-action="Index">Back to List</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

Views/SuccessStory/Edit.cshtml
@model LoveNottiesV2.Models.SuccessStory

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SuccessStory</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SuccessStoryID" />
            <div class="form-group">
                <label asp-for="SuccessStoryTitle" class="control-label"></label>
                <input asp-for="SuccessStoryTitle" class="form-control" />
                <span asp-validation-for="SuccessStoryTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SuccessStoryImageID" class="control-label"></label>
                <input asp-for="SuccessStoryImageID" class="form-control" />
                <span asp-validation-for="SuccessStoryImageID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SuccessStoryDescription" class="control-label"></label>
                <input asp-for="SuccessStoryDescription" class="form-control" />
                <span asp-validation-for="SuccessStoryDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/SuccessStory/Index.cshtml
@model IEnumerable<LoveNottiesV2.Models.SuccessStory>
@using LoveNottiesV2.Models.Repositories.Abstract;
@using LoveNottiesV2.Models.Repositories.Implemented;
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@inject IBlobService _IblobService

@{
    ViewData["Title"] = "Index";
}

<style>
    .parallax {
        /* The image used */
        background-image: url("https://lovenottiesstoragetest.blob.core.windows.net/backgroundimages/BgSS");
        /* Set a specific height */
        min-height: 500px;
        /* Create the parallax scrolling effect */
        background-attachment: fixed;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>


<h1 class="justify-content-center">Our Success Stories</h1>
@if (SignInManager.IsSignedIn(User) & User.IsInRole("Manager"))
{
    <p>
        <a class="btn btn-primary" asp-action="Create">Create New</a>
    </p>
}
<body>
    <div class="parallax">
    <div class="box">
        @foreach (var item in Model)
        {
            <div class="card text-white bg-primary mb-10" style="max-width: 20rem;">
                <div class="card-header">@Html.DisplayFor(modelItem => item.SuccessStoryTitle)</div>
                <div class="justify-content-center">
                    <image src="https://lovenottiesstoragetest.blob.core.windows.net/successimages/@(item.SuccessStoryID)" class="d-block user-select-none coverImage" width="10px" height="10px" focusable="false" role="img" preserveAspectRatio="xMidYMid slice" viewBox="0 0 318 180" style="font-size:1.125rem;text-anchor:middle" />
                </div>
                <div class="card-body">
                    <h6 class="card-body ">

                        @if (item.SuccessStoryDescription.Length >= 75)
                        {

                            @(item.SuccessStoryDescription.Substring(0, 75)) <a asp-controller="SuccessStory" asp-action="Details" asp-route-id="@(item.SuccessStoryID)">...Read More</a>
                        }
                        else
                        {
                            @(item.SuccessStoryDescription) <a asp-controller="SuccessStory" asp-action="Details" asp-route-id="@(item.SuccessStoryID)">...Read More</a>
                        }
                    </h6>

                    <div>
                        @if (SignInManager.IsSignedIn(User) & User.IsInRole("Manager"))
                        {
                            <a class="btn btn-outline-warning" asp-controller="SuccessStory" asp-action="Edit" asp-route-id="@(item.SuccessStoryID)">Edit</a>
                            <a class="btn btn-outline-danger" asp-controller="SuccessStory" asp-action="Delete" asp-route-id="@(item.SuccessStoryID)">Delete</a>
                        }
                    </div>
                </div>
            </div>
        }
    </div>
    </div>
</body>